- name: Add the user 'admin' with a bash shell to the user's groups
  user:
      name: admin
      password: "{{ 'admin' | password_hash('sha512') }}"
      create_home: yes
      shell: /bin/bash

- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
      path: /etc/hosts
      line: "{{ item.value }} {{ item.key }}"


- name: Create /home/admin/personal directory
  file:
    path: /home/admin/personal
    state: directory
    owner: admin
    group: admin
    mode: 0700

- name: Copy files into /home/admin/personal
  copy:
      src: "{{ item }}"
      dest: /home/admin/personal
      owner: admin
      mode: 0640
  with_items:
      - invoices2019.zip
      - Croatia 2019
      - Italy 2018
      - Mydata.xlsx
      - Romeo-and-Juliet.pdf
      - Treasure-Island.pdf

- name: install nfs server
  action: apt pkg=nfs-kernel-server state=present update_cache=yes
  tags:
    - nfs

- name: ensure nfs service is running (Ubuntu)
  action: service name={{item}} state=started
  tags:
    - nfs
  with_items:
    - nfs-kernel-server
